http {
  hostname = "0.0.0.0"
  hostname = ${?HTTP_HOSTNAME}
  port = 3000
  port = ${?HTTP_PORT}
  pathPrefix = ""
  pathPrefix = ${?HTTP_PATH_PREFIX}
}

oauth {
  jwt {
    algorithm = "HS256"
    algorithm = ${?OAUTH_JWT_ALGORITHM}
    secret = ${?OAUTH_JWT_SECRET}
    jwksUri = ${?OAUTH_JWT_JWKS_URI}
    publicKey = ${?OAUTH_JWT_PUBLIC_KEY}
    publicKeyPath = ${?OAUTH_JWT_PUBLIC_KEY_PATH}
    validate = true
    validate = ${?OAUTH_JWT_VALIDATE}
  }
}

attribute {
  collectors = [
    { collector = "PayloadScopeCollector" }
    { collector = "PayloadSubjectIdCollector" }
  ]
}

rule {
  collectors = [
    { collector = "ResourceActionScopeRuleCollector" }
    { collector = "ResourceActionPermissionRuleCollector" }
  ]
}
