services:
  app:
    build:
      context: .
      target: develop
    ports:
      - "3000:3000"
    volumes:
      - ./src:/home/node/src
      - ./config:/home/node/config
    env_file:
      - path: .env
        required: false
